DROP TABLE IF EXISTS schedule_job;
CREATE TABLE `schedule_job` (
  `job_id` INT(11) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键，任务ID',
  `job_name` VARCHAR(255) NOT NULL UNIQUE COMMENT '任务名称',
  `job_group` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '任务分组',
  `job_alias` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '任务别名',
  `job_desc` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '任务描述',
  `job_trigger` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '任务触发器',
  `job_status` VARCHAR(255) NOT NULL DEFAULT '1' COMMENT '任务状态（0:禁用 1:启用 2:删除）',
  `cron_expression` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '任务运行时间表达式',
  `url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '任务执行URL',
  `is_sync` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否异步（0:异步，1:同步）',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT '计划任务信息表'